/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icsia_final;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Cindy Liu
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Connection myconObj = null; 
    Statement mystatObj = null; 
    ResultSet myresObj = null;
    public MainForm() {
        initComponents();
        setData ();
    }

    public void setData (){
        try{
            myconObj = DriverManager.getConnection ("jdbc:derby://localhost:1527/ChenLegalServices", "Cindy", "123");
            mystatObj = myconObj. createStatement (); 
            myresObj = mystatObj. executeQuery ("Select * from Cindy.Clients");
            clientTable.setModel (DbUtils.resultSetToTableModel(myresObj));
            myresObj = mystatObj. executeQuery ("Select * from Cindy.Services");
            serviceTable.setModel (DbUtils.resultSetToTableModel(myresObj));
        }
        // name, phone, email, address, service, driverlicense
        catch (SQLException e){
            e.printStackTrace ();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ClientPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        cAddButton = new javax.swing.JButton();
        cNameTextField = new javax.swing.JTextField();
        cDeleteButton = new javax.swing.JButton();
        cNameLabel = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        phoneNumTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        driverLicenseLabel = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        serviceTextField = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cIDLabel = new javax.swing.JLabel();
        cIDTextField = new javax.swing.JTextField();
        shownRadioButton = new javax.swing.JRadioButton();
        notShownRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        paymentAmountTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paymentMethodTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        profitTextField = new javax.swing.JTextField();
        taxTextField = new javax.swing.JTextField();
        ServicePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        sAddButton3 = new javax.swing.JButton();
        sDeleteButton = new javax.swing.JButton();
        sNameTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        sNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sIDTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(clientTable);

        cAddButton.setText("Add");
        cAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAddButtonActionPerformed(evt);
            }
        });

        cNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNameTextFieldActionPerformed(evt);
            }
        });

        cDeleteButton.setText("Delete");
        cDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDeleteButtonActionPerformed(evt);
            }
        });

        cNameLabel.setText("Name: ");

        phoneNumLabel.setText("Phone Number:");

        phoneNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumTextFieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Email:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        addressLabel.setText("Address:");

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        driverLicenseLabel.setText("Driver License:");

        serviceLabel.setText("Service:");

        serviceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceTextFieldActionPerformed(evt);
            }
        });

        printButton.setText("Print Report");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Insert the client information below and click Add to add the client to the above table.");

        jLabel2.setText("Insert the ID of the client below and click Delete to delete the client from the above table. ");

        cIDLabel.setText("ID:");

        cIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIDTextFieldActionPerformed(evt);
            }
        });

        shownRadioButton.setText("Shown");
        shownRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shownRadioButtonActionPerformed(evt);
            }
        });

        notShownRadioButton.setText("Not Shown");
        notShownRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notShownRadioButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Payment Amount ($):");

        jLabel7.setText("Payment Method:");

        jLabel8.setText("Profit($):");

        jLabel9.setText("Tax($):");

        javax.swing.GroupLayout ClientPanelLayout = new javax.swing.GroupLayout(ClientPanel);
        ClientPanel.setLayout(ClientPanelLayout);
        ClientPanelLayout.setHorizontalGroup(
            ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(ClientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(ClientPanelLayout.createSequentialGroup()
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ClientPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(paymentAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClientPanelLayout.createSequentialGroup()
                                .addComponent(cNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ClientPanelLayout.createSequentialGroup()
                                .addComponent(phoneNumLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ClientPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClientPanelLayout.createSequentialGroup()
                                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serviceLabel)
                                    .addComponent(addressLabel))
                                .addGap(55, 55, 55)
                                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(serviceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(368, 368, 368)
                                .addComponent(cIDLabel))
                            .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cAddButton)
                                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ClientPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(paymentMethodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ClientPanelLayout.createSequentialGroup()
                                        .addComponent(driverLicenseLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(shownRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(notShownRadioButton)))))
                        .addGap(18, 18, 18)
                        .addComponent(cIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(printButton, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(ClientPanelLayout.createSequentialGroup()
                                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taxTextField)
                                    .addComponent(profitTextField))))))
                .addGap(29, 29, 29))
        );
        ClientPanelLayout.setVerticalGroup(
            ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientPanelLayout.createSequentialGroup()
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNameLabel)
                            .addComponent(cNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cIDLabel)
                            .addComponent(cIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumLabel)
                            .addComponent(phoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceLabel)
                            .addComponent(serviceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(driverLicenseLabel)
                            .addComponent(shownRadioButton)
                            .addComponent(notShownRadioButton)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addComponent(cDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(paymentAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(paymentMethodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cAddButton)
                    .addComponent(printButton))
                .addGap(16, 16, 16)
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(taxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Client", ClientPanel);

        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(serviceTable);

        sAddButton3.setText("Add");
        sAddButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAddButton3ActionPerformed(evt);
            }
        });

        sDeleteButton.setText("Delete");
        sDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDeleteButtonActionPerformed(evt);
            }
        });

        sNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameTextFieldActionPerformed(evt);
            }
        });

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        sNameLabel.setText("Name:");

        priceLabel.setText("Price:");

        jLabel3.setText("ID:");

        sIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sIDTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Insert the service information below and click Add to add the service to the above table.");

        jLabel5.setText("Insert the ID of the service below and click Delete to delete the service from the above table. ");

        javax.swing.GroupLayout ServicePanelLayout = new javax.swing.GroupLayout(ServicePanel);
        ServicePanel.setLayout(ServicePanelLayout);
        ServicePanelLayout.setHorizontalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(ServicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(ServicePanelLayout.createSequentialGroup()
                        .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ServicePanelLayout.createSequentialGroup()
                                .addComponent(sNameLabel)
                                .addGap(22, 22, 22)
                                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(sNameTextField)))
                            .addComponent(priceLabel))
                        .addGap(48, 48, 48)
                        .addComponent(sAddButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ServicePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(ServicePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(sIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sDeleteButton)
                        .addGap(40, 40, 40))))
        );
        ServicePanelLayout.setVerticalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServicePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sNameLabel)
                            .addComponent(sNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ServicePanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(sAddButton3))
                    .addGroup(ServicePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sDeleteButton))))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Service", ServicePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getNextID (String dbName){
        int id = 0; 
        try{
            myresObj = mystatObj. executeQuery ("Select COUNT(*) AS rowcount from Cindy." + dbName);
            myresObj.next();
            id = myresObj.getInt("rowcount"); 
            myresObj.close();
        }
        catch (SQLException e){
           e.printStackTrace();
        }
        System.out.print ("id:" + id + "   new id: " + (id+1));
        return id + 1;
    }
    
    private void cAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAddButtonActionPerformed
        // TODO add your handling code here:
        try{
            int id = getNextID ("clients");
            String name = cNameTextField.getText ();
            String email = emailTextField.getText (); 
            String phoneNum = phoneNumTextField.getText ();
            String address = addressTextField.getText();
            String service = serviceTextField.getText();
            double paymentAmount = Double.parseDouble(paymentAmountTextField.getText());
            String paymentMethod = paymentMethodTextField.getText ();
            
            PreparedStatement add = myconObj.prepareStatement("insert into Cindy.clients values (?,?,?,?,?,?,?,?,?)");
            add.setInt (1, id);
            add.setString (2,name);
            add.setString (3,phoneNum);
            add.setString (4,email);
            add.setString (5,address);
            add.setString (6,service);
            add.setString (7, showDL);
            add.setString (9,Double.toString (paymentAmount));
            add.setString (8,paymentMethod);
            // for check box add.setString (2,name);
            int row = add.executeUpdate();
        }
        catch (SQLException e){            
            e.printStackTrace ();
        }
        setData();
    }//GEN-LAST:event_cAddButtonActionPerformed

    private void cDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDeleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Delete from Cindy.clients where id =" + cIDTextField.getText();
            Statement delete = myconObj.createStatement();
            delete.executeUpdate(sql);
            cIDTextField.setText ("");
        }
        catch (SQLException e){
            e.printStackTrace();
        }
        setData();
    }//GEN-LAST:event_cDeleteButtonActionPerformed

    private void sAddButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAddButton3ActionPerformed
        // TODO add your handling code here:
        try{
            int id = getNextID ("services");
            String name = sNameTextField.getText ();
            String price = priceTextField.getText (); 

            PreparedStatement add = myconObj.prepareStatement("insert into Cindy.services values (?,?,?)");
            add.setInt (1, id);
            add.setString (2,name);
            add.setString (3,price);
            
            int row = add.executeUpdate();
        }
        catch (SQLException e){
            e.printStackTrace ();
        }
        setData();
    }//GEN-LAST:event_sAddButton3ActionPerformed

    private void sDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDeleteButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Delete from Cindy.services where id =" + sIDTextField.getText();
            Statement delete = myconObj.createStatement();
            delete.executeUpdate(sql);
            sIDTextField.setText ("");
        }
        catch (SQLException e){
            e.printStackTrace();
        }
        setData();
    }//GEN-LAST:event_sDeleteButtonActionPerformed

    private void sNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void cNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNameTextFieldActionPerformed

    private void phoneNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void serviceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private String getProfit ()
    {
        double profit = 0;
        
        try{
            Statement st = myconObj.createStatement(); 
            ResultSet res = st.executeQuery("SELECT SUM(paymentAmount) FROM Cindy.clients");
            while (res.next()) {
                double c = res.getDouble(1);
                profit = profit + c;
            }
        }
        catch (SQLException e){
             e.printStackTrace ();
        }
        return df2.format(profit);
    }
    private String getTax ()
    {
        double profit = Double.parseDouble (getProfit());
        double taxRate = 0.13;
        double t = profit * taxRate;
        return df2.format(t);
    }
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        profitTextField.setText (getProfit());
        taxTextField.setText (getTax());
    }//GEN-LAST:event_printButtonActionPerformed

    private void cIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cIDTextFieldActionPerformed

    private void sIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sIDTextFieldActionPerformed

    private void shownRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shownRadioButtonActionPerformed
        // TODO add your handling code here:
        showDL = "Yes";
    }//GEN-LAST:event_shownRadioButtonActionPerformed

    private void notShownRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notShownRadioButtonActionPerformed
        // TODO add your handling code here:
        showDL = "No";
    }//GEN-LAST:event_notShownRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientPanel;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton cAddButton;
    private javax.swing.JButton cDeleteButton;
    private javax.swing.JLabel cIDLabel;
    private javax.swing.JTextField cIDTextField;
    private javax.swing.JLabel cNameLabel;
    private javax.swing.JTextField cNameTextField;
    private javax.swing.JTable clientTable;
    private javax.swing.JLabel driverLicenseLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton notShownRadioButton;
    private javax.swing.JTextField paymentAmountTextField;
    private javax.swing.JTextField paymentMethodTextField;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JTextField phoneNumTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField profitTextField;
    private javax.swing.JButton sAddButton3;
    private javax.swing.JButton sDeleteButton;
    private javax.swing.JTextField sIDTextField;
    private javax.swing.JLabel sNameLabel;
    private javax.swing.JTextField sNameTextField;
    private javax.swing.JLabel serviceLabel;
    private javax.swing.JTable serviceTable;
    private javax.swing.JTextField serviceTextField;
    private javax.swing.JRadioButton shownRadioButton;
    private javax.swing.JTextField taxTextField;
    // End of variables declaration//GEN-END:variables
    private String showDL; 
    private static DecimalFormat df2 = new DecimalFormat(".##");
}
